apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: qzbldufgo-go 
  janus-idp.io/tekton: qzbldufgo-go
  backstage.io/kubernetes-id: qzbldufgo-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qzbldufgo-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  